name: "Install Podman 5.x"
description: "Installs/updates Podman to v5 from the Kubic repository on Ubuntu."

inputs:
  ubuntu-version:
    description: "The Ubuntu version codename for the Kubic repository."
    required: false
    default: "23.10"

runs:
  using: "composite"
  steps:
    - name: Update podman to 5.x
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ubuntu_version='${{ inputs.ubuntu-version }}'
        echo "INFO: Using Ubuntu version '${ubuntu_version}' for Kubic repository."

        echo "INFO: Adding Kubic repository..."
        sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
        curl -fsSL "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kubic.gpg

        echo "INFO: Updating package list..."
        sudo apt-get update -qq

        echo "INFO: Installing CRIU dependencies..."
        sudo apt-get install --allow-unauthenticated -qq -y libprotobuf32t64 python3-protobuf libnet1

        echo "INFO: Installing CRIU manually..."
        curl -sLO http://archive.ubuntu.com/ubuntu/pool/universe/c/criu/criu_3.16.1-2_amd64.deb && sudo dpkg -i criu_3.16.1-2_amd64.deb

        echo "INFO: Installing Podman..."
        sudo apt-get -qq -y install --allow-unauthenticated podman || {
          echo "WARN: Primary installation failed. Trying fallback repository..."
          sudo sh -c "echo 'deb http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
          curl -fsSL "http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kubic-fallback.gpg
          sudo apt-get --allow-insecure-repositories update -qq
          sudo apt-get --allow-unauthenticated -y install podman
        }

        echo "INFO: Podman installation complete."
        podman version

    - name: Install Podman on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "Installing Podman..."
        curl --output podman-setup.exe -L https://github.com/containers/podman/releases/download/v5.3.2/podman-5.3.2-setup.exe
        # Start the installer and wait for it to complete
        Start-Process -FilePath .\podman-setup.exe -ArgumentList "/install", "/passive", "/norestart", "/log podman-logs.txt" -Wait
        # Check the logs for debugging purposes
        Get-Content podman-logs.txt

    - name: Initialize Podman Machine on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "Adding Podman to PATH for this session..."
        $env:PATH += ";C:\Program Files\RedHat\Podman"
        podman --version
        echo "Initializing Podman machine..."
        podman machine init --now
